export const PROMISE = 'PROMISE';
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

export const GET_AUTH = 'GET_AUTH';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';

export const GET_API_KEY = 'GET_API_KEY';
export const GET_API_KEY_SUCCESS = 'GET_API_KEY_SUCCESS';
export const GET_API_KEY_ERROR = 'GET_API_KEY_ERROR';

export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const LOAD_WIKI = 'LOAD_WIKI_PAGE';
export const LOAD_WIKI_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_WIKI_FAILURE = 'LOAD_DATA_FAILURE';

export const SAVE_WIKI = 'SAVE_WIKI';
export const SAVE_WIKI_SUCCESS = 'SAVE_WIKI_SUCCESS';
export const SAVE_WIKI_ERROR = 'SAVE_WIKI_ERROR';
export const SET_PAGE_TEXT = 'SET_PAGE_TEXT';


export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE';